var asignatura = new Object();
asignatura.nombre = "Software y estándares en la Web";
asignatura.titulacion = "Grado en Ingeniería Informática del Software";
asignatura.centro = "Escuela de Ingeniería Informática";
asignatura.universidad = "Universidad de Oviedo";
asignatura.curso = "2020-2021";
var alumno = new Object();
alumno.nombre = "Aarón García García";
alumno.email = "uo277819@uniovi.es";